<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang = "it">
	<head>
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
		<%@ include file="/partials/head.jsp" %>			
		<title>Condizioni generali</title>		
	</head>
	<body>
		<%@ include file="/partials/header.jsp" %>				
	<div id="content">
		<div id="content-content">
			<div id="condizioni_generali">
			<h1><strong>CONDIZIONI GENERALI DI UTILIZZO DEL SITO INTERNET </strong></h1>	
			<p>L’utilizzo del sito EAT MEAT2.0 comporta l’accettazione da parte dell’utente delle condizioni generali di contratto di seguito riportate (le “Condizioni Generali”). Prima dell’accettazione, è responsabilità dell’utente procedere alla lettura attenta e consapevole delle Condizioni Generali. Ove l’utente non intenda accettare le Condizioni Generali, quest’ultimo si deve astenere dall’accedere alle informazioni, ai dati e, in generale, ai contenuti informativi di proprietà di Horta Srl pubblicati all’interno del Sito.</p>	 	
			<p>Le presenti condizioni generali si applicano al Sito, alla navigazione nel Sito, alla richiesta di registrazione alle sezioni ad accesso riservato del Sito (ivi compresa la sezione dedicata ai Servizi Riservati) alla richiesta di erogazione e all’erogazione dei Servizi.</p>
			<p>L'amministratore potrà modificare e/o aggiornare, in tutto o in parte, le presenti condizioni generali. Le modifiche e/o gli aggiornamenti saranno notificati agli Utenti mediante specifica informazione sulla Home Page del Sito non appena adottati e saranno vincolanti non appena pubblicati sul Sito, in sostituzione della precedente versione. Si consiglia, pertanto, di accedere con regolarità a questa pagina per verificare la pubblicazione della versione più recente e aggiornata.</p>	
			<p>Ogniqualvolta l’Utente navighi nel Sito, accetta di aderire alle condizioni generali stabilite nel momento in cui avviene l’accesso. Qualora l’Utente non volesse accettare tali condizioni generali, è tenuto a lasciare il Sito.</p>	
			<p>La messa a disposizione di alcuni Servizi o sezioni del Sito può essere soggetta a ulteriori o diversi termini e condizioni di regolamentazione (“condizioni particolari”): l’Utente dichiara sin da ora di essere a conoscenza e accettare che per l’accesso a dette sezione e/o la fruizione di detti Servizi deve conformarsi a tali condizioni particolari.</p>	
			<p>Salvo ove diversamente specificato, il Sito, i suoi contenuti e i Servizi sono forniti all’Utente in un’unica soluzione al momento di ciascuna connessione da parte dell’Utente. L’Utente ne richiede e accetta la loro fornitura immediata.</p>	 	
			<p><strong>1 – PARTI –</strong>Le presenti Condizioni Generali sono stipulate da EAT.MEAT 2.0, con sede legale a Eboli, Via Umberto Nobile 22, C.F./P.IVA 000000000, iscrizione al Registro delle Imprese di salerno e R.E.A. 17020091 e il singolo utente del Sito (sia esso una persona fisica, persona giuridica o altro ente), il quale agisca per conto proprio e/o per conto dell’ente che rappresenta (l’Utente).</p>	
			<p><strong>2 – ACCETTAZIONE – </strong>Le Condizioni Generali si intendono accettate dall’Utente con la sua navigazione nel sito; qualora l’Utente non volesse accettare le presenti Condizioni Generali è tenuto a lasciare il Sito. Le condizioni particolari relative ad alcuni Servizi o Sezioni del Sito si intendono accettate nel momento in cui l’Utente sceglie (ciccando o contrassegnando) l’apposito campo “ACCETTO” in calce alle condizioni stesse.</p>	
			<p><strong>3 – OGGETTO –</strong>Oggetto delle presenti Condizioni Generali è la fornitura all’Utente a titolo gratuito ed a tempo indeterminato della consultazione del Sito secondo i termini e con i limiti di seguito stabiliti.</p>	
			<p><strong>4 – Accesso e fruizione del Sito</strong>EAT.MEAT 2.0 mette a disposizione l’accesso al Sito e i suoi contenuti informativi nello stato e alle condizioni in cui si trovano nel momento in cui l’Utente vi accede, con le seguenti precisazioni:
						(a) i contenuti del Sito non sono esenti da vizi, difetti o errori e non sono finalizzati a un uso commerciale e/o professionale;
						(b) il Sito e i suoi contenuti non sono forniti per il raggiungimento di obiettivi o risultati particolari perseguiti dall’Utente;
						(c) non è fornito il controllo dei siti di terzi o dei contenuti forniti dai terzi, presenti nel Sito o ai quali sia possibile accedere tramite i collegamenti presenti all’interno del Sito, né il controllo dell’esattezza e/o dell’aggiornamento di detti collegamenti.</p>	
			<p><strong>5 – PROPRIETÀ INTELLETTUALE –</strong>L’Utente riconosce ed accetta che tutte le informazioni e i dati pubblicati all’interno del Sito ed il Sito stesso, sono di esclusiva proprietà di EAT META2.0 e, in quanto tali, sono protetti dalle norme nazionali e dalle convenzioni internazionali in materia di proprietà intellettuale e industriale.</p>	
			<p><strong>6 – USI NON CONSENTITI –</strong>è fatto divieto all’Utente, in assenza del preventivo consenso scritto di EAT.MEAT 2.0,di pubblicare, riprodurre in copie, memorizzare, trasmettere in forma elettronica o con altri mezzi, creare riassunti e/o estratti, distribuire, commercializzare, tradurre e/o comunque utilizzare, in tutto o in parte, il Sito per qualunque finalità di tipo economico e/o commerciale e/o comunque di carattere non strettamente privato e personale. La violazione della presente disposizione – oltre ad esporre l’Utente a responsabilità contrattuale – comporta la segnalazione da parte di EAT.MEAT 2.0 all’Autorità Giudiziaria per l’accertamento delle relative responsabilità penali e/o amministrative e la conseguente eventuale applicazione delle sanzioni previste dalla legge.</p>	
			<p><strong>7 – ACCURATEZZA DEI DATI PUBBLICATI DA EAT.MEAT 2.0–</strong>In considerazione della natura meramente informativa dei Contenuti pubblicati sul Sito, l’Utente riconosce e accetta che EAT.MEAT 2.0 non possa essere ritenuta responsabile, salvi i casi accertati di dolo o colpa grave, per gli eventuali danni che possano derivare dall’uso del Sito o dai Contenuti tratti da quest’ultimo. EAT.MEAT 2.0 impiega ogni ragionevole sforzo per pubblicare sul Sito informazioni accurate ed aggiornate. In ogni caso, EAT.MEAT 2.0 non fornisce alcuna garanzia in merito all’accuratezza e aggiornamento dei contenuti pubblicati all’interno delle pagine del Sito, né si assume alcuna responsabilità in merito ad eventuali errori od omissioni ad esso relative.</p>	
			<p><strong>8 – ACCURATEZZA DEGLI ALTRI DATI –</strong>L’Utente prende atto e accetta che EAT.MEAT 2.0 non ha alcun controllo sui siti esterni accessibili tramite i collegamenti eventualmente presenti nel Sito e, pertanto, non è responsabile dei contenuti dei siti collegati. L’Utente dichiara di conoscere che EAT.MEAT 2.0 non può garantire la completezza e/o esattezza delle informazioni contenute nel Sito che provengono da fonti diverse da EAT.MEAT 2.0, né può evitare che informazioni provenienti da fonti comunque ritenute attendibili possano in alcune circostanze risultare inesatte, incomplete o non aggiornate per problemi tecnici o cause esterne al controllo di EAT.MEAT 2.0.</p>	
			<p><strong>9 – SOSPENSIONE DEL SERVIZIO –</strong>L’Utente prende atto e accetta che EAT.MEAT 2.0 non è responsabile per i danni derivanti da eventuali interruzioni, sospensioni, ritardi o anomalie nella fornitura del Sito, dipendenti dalla fornitura di energia elettrica o del servizio telefonico, dovuti a caso fortuito o forza maggiore oppure ad altre cause collegate al mezzo tramite il quale il Sito viene pubblicato.</p>	
			<p><strong>10 – ESCLUSIONE DI GARANZIA –</strong>L’utilizzo e la navigazione nel Sito avviene sotto la responsabilità dell’Utente. EAT.MEAT 2.0 ed i suoi dipendenti, amministratori, collaboratori o terzi impegnati nella creazione, produzione o messa on line del Sito non potranno essere considerati responsabili per ogni e qualsiasi danno che dovesse derivare all’Utente dall’accesso e/o da qualsivoglia utilizzo del Sito. Fermo restando quanto sopra, EAT.MEAT 2.0 dichiara che il Sito viene messo a disposizione dell’Utente così com’è, senza nessuna garanzia, espressa o implicita, incluse, a mero titolo esemplificativo, adattabilità o fruibilità a un fine specifico.</p>	
			<p><strong>11 – Copyright</strong>, domini, marchi e segni distintivi – Tutti i testi, le immagini, i suoni, i video, i database, i software e ogni altro contenuto presente nel Sito (da ora in avanti denominati “contenuti”) sono oggetto di proprietà intellettuale e/o industriale spettante a EAT.MEAT 2.0 o ai suoi fornitori. Ogni azione riservata al titolare dei diritti dalle leggi nazionali e internazionali in materia di proprietà intellettuale o industriale (compreso il diritto d’autore) compiuta senza l’autorizzazione del titolare è perseguibile civilmente e penalmente.</p>	
			<p><strong>12 – VARIAZIONI –</strong>EAT.MEAT 2.0 si riserva il diritto di modificare le Condizioni Generali in qualunque momento e senza preavviso. Al fine di garantire la comunicazione delle eventuali variazioni delle Condizioni Generali, le modifiche e/o gli aggiornamenti saranno notificati agli Utenti mediante specifica informazione sulla Home Page del Sito non appena adottati e saranno vincolanti non appena pubblicati sul Sito, in sostituzione della precedente versione. L’Utente prende atto ed accetta, altresì, che HORTA ha il diritto di modificare e/o oscurare, in qualsiasi momento ed a propria discrezione, in tutto o in parte, i contenuti del Sito, senza obbligo di preavviso.</p>	
			<p><strong>13 – LEGGE APPLICABILE –</strong>Le Condizioni Generali del Sito sono regolate dalla legge italiana.</p>		
	
	
		
				
	</div>		
		</div>
			</div>	

		<%@ include file="/partials/footer.jsp" %>
	
	</body>
</html>
